FROM node:16 AS build-env
COPY src_node /app
WORKDIR /app/src

# RUN npm i

RUN npm init --yes
RUN npm install request --save

# FROM gcr.io/distroless/nodejs:16
# COPY --from=build-env /app /app
# WORKDIR /app
# CMD ["hello.js"]
